name: Test

triggers:
  - cron:
      when: "* * * * *"
  - http:
      request:
        id: example_http
        method: "GET"
        url: "https://example.com"
        when:
          changed:
            delay: 12000

graph:
  - id: formatted
    step:
      awk:
        input:
          trigger: example_http
        script: "{print}"

writers:
  - email:
      address: inquiry@midstall.com
      template: "${graph.formatted}"
