name: Test

triggers:
  - http:
      request:
        id: example_http
        method: "GET"
        url: "https://example.com"
        when:
          changed:
            delay: 12

graph:
  - id: formatted
    step:
      awk:
        input:
          trigger:
            id: example_http
            key: body
        script: "{print}"

writers:
  - email:
      address: inquiry@midstall.com
      template: "<%= read_graph('formatted') %>"
